export enum PokemonType {
  NORMAL = 'normal' as any,
  FIGHTING = 'fighting' as any,
  FLYING = 'flying' as any,
  POISON = 'poison' as any,
  GROUND = 'ground' as any,
  ROCK = 'rock' as any,
  BUG = 'bug' as any,
  GHOST = 'ghost' as any,
  STEEL = 'steel' as any,
  FIRE = 'fire' as any,
  WATER = 'water' as any,
  GRASS = 'grass' as any,
  ELECTRIC = 'electric' as any,
  PSYCHIC = 'psychic' as any,
  ICE = 'ice' as any,
  DRAGON = 'dragon' as any,
  DARK = 'dark' as any,
  FAIRY = 'fairy' as any,
  UNKNOWN = 'unknown' as any,
  SHADOW = 'shadow' as any,
}

export enum PokemonTypeBackgroundColor {
  NORMAL = 'salmon',
  FIGHTING = 'olive',
  FLYING = 'skyblue',
  POISON = 'darkslateblue',
  GROUND = 'sienna',
  ROCK = 'dimgray',
  BUG = 'indianred',
  GHOST = 'darkslategray',
  STEEL = 'silver',
  FIRE = 'darkorange',
  WATER = 'dodgerblue',
  GRASS = 'limegreen',
  ELECTRIC = 'gold',
  PSYCHIC = 'rebeccapurple',
  ICE = 'lightcyan',
  DRAGON = 'darkred',
  DARK = 'midnightblue',
  FAIRY = 'pink',
  UNKNOWN = 'azure',
  SHADOW = 'black',
}

export enum PokemonTypeColor {
  NORMAL = 'black',
  FIGHTING = 'white',
  FLYING = 'black',
  POISON = 'white',
  GROUND = 'white',
  ROCK = 'white',
  BUG = 'white',
  GHOST = 'white',
  STEEL = 'black',
  FIRE = 'black',
  WATER = 'white',
  GRASS = 'black',
  ELECTRIC = 'black',
  PSYCHIC = 'white',
  ICE = 'black',
  DRAGON = 'white',
  DARK = 'white',
  FAIRY = 'black',
  UNKNOWN = 'black',
  SHADOW = 'white',
}
